#!/usr/bin/env sh

# Ctrlp*     -> https://github.com/ctrlpvim/ctrlp.vim
# Sandwich*  -> https://github.com/machakann/vim-sandwich
# Commentary -> https://github.com/tpope/vim-commentary
# Lexima     -> https://github.com/cohama/lexima.vim
# Context    -> https://github.com/wellle/context.vim




### Check & Funcs
#################

if ! command -v vim >/dev/null 2>&1 || ! command vim --version | grep -q 'Vi IMproved 9'; then
    printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
    printf "\n%s\n" "Install Vim9 and run this script again"
    exit 1
fi
# ---
warning_message () {
    if [ "$(id -u)" = 0 ]; then
        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
        exit 1
    fi
}
# ---
error_echo () {
    printf "ERROR: %s\n" "$1" >&2
    exit 1
}
# ---
reset_plugin() {
    printf "\n%s\n" "$OPERATION"
    if [ -d "$PLUGIN" ]; then
        command git -C "$PLUGIN" pull
    else
        command git clone "$REPOSITORY" "$PLUGIN"
    fi
}




### Path & Dependencies
#######################

warning_message
SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
command sudo apt-get update || error_echo "update repos"
command sudo apt-get upgrade -qq -y || error_echo "upgrade repos"
command sudo apt-get install -qq -y git || error_echo "install packages"




### Start
#########

VIM=${HOME}/.vim
START="${VIM}/pack/plug/start"
command mkdir -p "$VIM"
command mkdir -p "$START"
[ -d "${VIM}/plugin" ] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
# ---
OPERATION="RESETTING CTRLP"
REPOSITORY="https://github.com/ctrlpvim/ctrlp.vim.git"
PLUGIN="${START}/ctrlp"
reset_plugin
# ---
OPERATION="RESETTING SANDWICH"
REPOSITORY="https://github.com/machakann/vim-sandwich.git"
PLUGIN="${START}/sandwich"
reset_plugin
# ---
OPERATION="RESETTING COMMENTARY"
REPOSITORY="https://github.com/tpope/vim-commentary.git"
PLUGIN="${START}/commentary"
reset_plugin
# ---
OPERATION="RESETTING LEXIMA"
REPOSITORY="https://github.com/cohama/lexima.vim.git"
PLUGIN="${START}/lexima"
reset_plugin
# ---
OPERATION="RESETTING CONTEXT"
REPOSITORY="https://github.com/wellle/context.vim.git"
PLUGIN="${START}/context"
reset_plugin




### Finish
##########

printf "\n%s\n" "setup complete"
