#!/usr/bin/env bash

# Ctrlp*     -> https://github.com/ctrlpvim/ctrlp.vim
# Sandwich*  -> https://github.com/machakann/vim-sandwich
# Commentary -> https://github.com/tpope/vim-commentary
# Lexima     -> https://github.com/cohama/lexima.vim
# Context    -> https://github.com/wellle/context.vim




### Check & Funcs
#################

RED='\033[1;36m'
NC='\033[0m'
# ---
if [[ ! -x "$(command -v "vim")" || ! "$(command vim --version | grep -oE 'Vi IMproved 9')" == "Vi IMproved 9" ]]; then
    printf "\n${RED}%s${NC}"   "═══════ Warning: Vim9 not found ══════"
    printf "\n${RED}%s${NC}\n" "Install Vim9 and run this script again"
    exit 1
fi
# ---
function warning-message () {
    if [[ "$(id -u)" = 0 ]]; then
        printf "\n${RED}%s${NC}"     "This script MUST NOT be run as root user since it makes changes"
        printf "\n${RED}%s${NC}"     "to the \$HOME directory of the \$USER executing this script."
        printf "\n${RED}%s${NC}"     "The \$HOME directory of the root user is, of course, '/root'."
        printf "\n${RED}%s${NC}"     "We don't want to mess around in there. So run this script as a"
        printf "\n${RED}%s${NC}\n" "normal user. You will be asked for a sudo password when necessary."
        exit 1
    fi
}
# ---
function error-echo () {
    printf "${RED}ERROR: %s${NC}\n" "$1" >&2
    exit 1
}
# ---
function reset-plugin () {
    printf "\n${RED}%s${NC}\n" "${OPERATION}"
    if [[ -d "${PLUGIN}" ]]; then
        command git -C "${PLUGIN}" pull
    else
        command git clone "${REPOSITORY}" "${PLUGIN}"
    fi
}




### Path & Dependencies
#######################

warning-message
SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
"${SCRIPTPATH}/base/fetch.sh"
command sudo apt-get install -qq -y git exuberant-ctags || error-echo "installing from apt"




### Start
#########

VIM=${HOME}/.vim && command mkdir -p "${VIM}"
START="${VIM}/pack/plug/start" && command mkdir -p "${START}"
[[ -d "${VIM}/plugin" ]] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
# ---
OPERATION="RESETTING CTRLP"
REPOSITORY="https://github.com/ctrlpvim/ctrlp.vim.git"
PLUGIN="${START}/ctrlp"
reset-plugin
# ---
OPERATION="RESETTING SANDWICH"
REPOSITORY="https://github.com/machakann/vim-sandwich.git"
PLUGIN="${START}/sandwich"
reset-plugin
# ---
OPERATION="RESETTING COMMENTARY"
REPOSITORY="https://github.com/tpope/vim-commentary.git"
PLUGIN="${START}/commentary"
reset-plugin
# ---
OPERATION="RESETTING LEXIMA"
REPOSITORY="https://github.com/cohama/lexima.vim.git"
PLUGIN="${START}/lexima"
reset-plugin
# ---
OPERATION="RESETTING CONTEXT"
REPOSITORY="https://github.com/wellle/context.vim.git"
PLUGIN="${START}/context"
reset-plugin




### Finish
##########

printf "\n${RED}%s${NC}\n" "setup complete"
