#!/usr/bin/env sh

# VSCode reset with just few tweaks and GitHub-Copilot extension:
# https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
# ---
# VSCode is not included in the Debian repos,
# install it separately: https://code.visualstudio.com/.




### Functions
#############

sudo_privilege () {
    id -Gn 2>/dev/null | grep -qw "sudo"
}




### Checks
##########

if [ "$(id -u)" -eq 0 ]; then
    printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
    printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
    printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
    printf "\n%s"   "We don't want to mess around in there. So run this script as a"
    printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
    exit 1
fi
# ---
if ! command -v code >/dev/null 2>&1; then
    printf "\n%s"   "═══════ Warning: VSCode not found ══════"
    printf "\n%s\n" "Install VSCode and run this script again"
    exit 1
fi




### Podeen-Code
###############

cat << EOF
.   .   ___         _                 ___         _
|\\_/|  | _ \\___  __| |___ ___ _ _    / __|___  __| |___
(O.o)  |  _/ _ \\/ _\` / -_) -_) ' \\  | (__/ _ \\/ _\` / -_)
(> <)  |_| \\___/\\__,_\\___\\___|_||_|  \\___\\___/\\__,_\\___|

EOF




### Path & Dependencies
#######################

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
if sudo_privilege; then
    sudo sh -c '
        apt-get update && apt-get upgrade -qq -y --allow-downgrades &&
        apt-get install -qq -y gnome-keyring dash bash git python3-full python3-pip black fonts-cascadia-code
    '
fi




### Start
#########

for EXTENSION in $(\code --list-extensions); do
    \code --uninstall-extension "$EXTENSION" >/dev/null 2>&1
done
\code --install-extension github.copilot
\code --install-extension ms-python.python
\code --install-extension ms-python.black-formatter
\code --install-extension ms-toolsai.jupyter
\code --install-extension monokai.theme-monokai-pro-vscode
# ---
BASE="${HOME}/.config/Code/User"
if mkdir -p "$BASE"; then
    cat "${SCRIPTPATH}/code/settings.json" > "${BASE}/settings.json"
    cat "${SCRIPTPATH}/code/keybindings.json" > "${BASE}/keybindings.json"
fi




### Finish
##########

printf "\n%s\n" "setup complete"
