#!/usr/bin/env sh

# VSCode reset with just few tweaks and GitHub-Copilot extension:
# https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
# ---
# VSCode is not included in the Debian repos,
# install it separately: https://code.visualstudio.com/.




### Check & Funcs
#################

version_check () {
    if ! command -v code >/dev/null 2>&1; then
        printf "\n%s"   "═══════ Warning: VSCode not found ══════"
        printf "\n%s\n" "Install VSCode and run this script again"
        exit 1
    fi
}
# ---
warning_message () {
    if [ "$(id -u)" = 0 ]; then
        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
        exit 1
    fi
}




### Path & Dependencies
#######################

version_check
warning_message
SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
[ -f "${SCRIPTPATH}/podeen.txt" ] && cat "${SCRIPTPATH}/podeen.txt"
command sudo apt-get update
command sudo apt-get upgrade -qq -y
command sudo apt-get install -qq -y gnome-keyring dash bash git fonts-cascadia-code




### Start
#########

BASE="${HOME}/.config/Code/User"
command mkdir -p "$BASE"
for EXTENSION in $(command code --list-extensions); do
    command code --uninstall-extension "$EXTENSION" >/dev/null 2>&1
done
# ---
command code --install-extension github.copilot
cat "${SCRIPTPATH}/code/settings.json" > "${BASE}/settings.json"
cat "${SCRIPTPATH}/code/keybindings.json" > "${BASE}/keybindings.json"




### Finish
##########

printf "\n%s\n" "setup complete"
