#!/usr/bin/env sh

# This base setup script will install a minimal work environment,
# complete with all the bells and whistles needed to start working properly.
# ---
# There are no worries of losing a potential old configuration: il will be
# stored in a separate folder in order to be restored manually if needed.
# ---
# Other packages not included here can be installed separately,
# suggestions: input-remapper, dconf-editor, gnome-shell-extension-manager.




### Check & Funcs
#################

if [ -d "${HOME}/.podeen-recovery" ]; then
    printf "\n%s"   "════════════════ Warning: podeen already set ════════════════"
    printf "\n%s\n" "Remove ~/.podeen-recovery directory and run this script again"
    exit 1
fi
# ---
warning_message () {
    if [ "$(id -u)" = 0 ]; then
        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
        exit 1
    fi
}
# ---
error_echo () {
    printf "ERROR: %s\n" "$1" >&2
    exit 1
}
# ---
store_conf () {
    backup_conf () {
        if [ -f "$1" ]; then
            if [ -L "$1" ]; then
                command unlink "$1"
            else
                mv "$1" "${RESTORE}/"
            fi
        fi
    }
    RESTORE="${HOME}/.podeen-recovery"
    command mkdir -p "$RESTORE"
    backup_conf "${HOME}/.bash_logout"
    backup_conf "${HOME}/.bashrc"
    backup_conf "${HOME}/.profile"
    backup_conf "${HOME}/.tmux.conf"
    backup_conf "${HOME}/.vimrc"
    backup_conf "${HOME}/.local/bin/fetch.sh"
}




### Path & Dependencies
#######################

warning_message
SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
command sudo apt-get update || error_echo "update repos"
command sudo apt-get upgrade -qq -y || error_echo "upgrade repos"
command sudo apt-get install -qq -y bash bash-completion fzy file fd-find xclip trash-cli \
      procps less git tmux vim exuberant-ctags wamerican || error_echo "install packages"




### Start
#########

store_conf
cp "${SCRIPTPATH}/base/.bash_logout" "${HOME}/"
cp "${SCRIPTPATH}/base/.bashrc" "${HOME}/"
cp "${SCRIPTPATH}/base/.profile" "${HOME}/"
cp "${SCRIPTPATH}/base/.tmux.conf" "${HOME}/"
cp "${SCRIPTPATH}/base/.vimrc" "${HOME}/"
# ---
command sudo chsh -s "$(command -v bash)" "$USER" || error_echo "change shell"
command mkdir -p "${HOME}/.local/bin/"
cp "${SCRIPTPATH}/base/fetch.sh" "${HOME}/.local/bin/"




### Finish
##########

printf "\n%s\n" "setup complete"
