#!/usr/bin/env sh

# Ctrlp*     -> https://github.com/ctrlpvim/ctrlp.vim
# Copilot*   -> https://github.com/github/copilot.vim
# Sandwich*  -> https://github.com/machakann/vim-sandwich
# Commentary -> https://github.com/tpope/vim-commentary
# Lexima     -> https://github.com/cohama/lexima.vim
# Context    -> https://github.com/wellle/context.vim




### Functions
#############

sudo_privilege () {
    id -Gn 2>/dev/null | grep -qw "sudo"
}
# ---
reset_plugin() {
    printf "\n%s\n" "$OPERATION"
    if [ -d "$PLUGIN" ]; then
        \git -C "$PLUGIN" pull
    else
        \git clone "$REPOSITORY" "$PLUGIN"
    fi
}




### Checks
##########

if [ "$(id -u)" -eq 0 ]; then
    printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
    printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
    printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
    printf "\n%s"   "We don't want to mess around in there. So run this script as a"
    printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
    exit 1
fi
# ---
if ! command -v vim >/dev/null 2>&1 || ! \vim --version | grep -q 'Vi IMproved 9'; then
    printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
    printf "\n%s\n" "Install Vim9 and run this script again"
    exit 1
fi




### Podeen-Plug
###############

cat << EOF
.   .   ___         _                ___ _
|\\_/|  | _ \\___  __| |___ ___ _ _   | _ \\ |_  _ __ _
(O.o)  |  _/ _ \\/ _\` / -_) -_) ' \\  |  _/ | || / _\` |
(> <)  |_| \\___/\\__,_\\___\\___|_||_| |_| |_|\\_,_\\__, |
                                               |___/

EOF




### Path & Dependencies
#######################

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
if sudo_privilege; then
    sudo sh -c '
        apt-get update && apt-get upgrade -qq -y &&
        apt-get install -qq -y git nodejs
    '
fi




### Start
#########

VIM=${HOME}/.vim
START="${VIM}/pack/plug/start"
mkdir -p "$START"
[ -d "${VIM}/plugin" ] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
# ---
OPERATION="RESETTING CTRLP"
REPOSITORY="https://github.com/ctrlpvim/ctrlp.vim.git"
PLUGIN="${START}/ctrlp"
reset_plugin
# ---
OPERATION="RESETTING COPILOT"
REPOSITORY="https://github.com/github/copilot.vim.git"
PLUGIN="${START}/copilot"
reset_plugin
# ---
OPERATION="RESETTING SANDWICH"
REPOSITORY="https://github.com/machakann/vim-sandwich.git"
PLUGIN="${START}/sandwich"
reset_plugin
# ---
OPERATION="RESETTING COMMENTARY"
REPOSITORY="https://github.com/tpope/vim-commentary.git"
PLUGIN="${START}/commentary"
reset_plugin
# ---
OPERATION="RESETTING LEXIMA"
REPOSITORY="https://github.com/cohama/lexima.vim.git"
PLUGIN="${START}/lexima"
reset_plugin
# ---
OPERATION="RESETTING CONTEXT"
REPOSITORY="https://github.com/wellle/context.vim.git"
PLUGIN="${START}/context"
reset_plugin




### Finish
##########

printf "\n%s\n" "setup complete"
